require('./findGlobals')
require('./inspectGlobals')
require('./inspectImports')
require('./inspectEsmImports')
require('./inspectPrimordialAssignments')
require('./inspectSesCompat')
require('./util')
