ignores:
  # monorepo deps
  - 'ava'
  # tests - used in tests
  - 'lavamoat-browserify'
  - 'keccak'
  # tests - fake packages
  - 'banana'
  - 'two'
  - 'one'
  - 'victim'
  - 'attacker'
  - 'three'
  - 'a'
  - 'b'
  - 'c'
  # invoked as executable only
  - 'lavamoat'
  # types
  - '@lavamoat/types'
