ignore-dirs: 'lib'
ignores:
  - 'ses'
  # monorepo deps
  - 'ava'
  - '@typescript-eslint/parser'
  # tests - fake packages
  - 'abc'
  - 'xyz'
  - 'two'
  - 'three'
  - 'thisChecker'
  - 'someClass'
  - 'one'
  # types
  - '@types/json-stable-stringify'
  - '@types/merge-deep'
  - '@babel/types'
  - '@lavamoat/types'
  - 'type-fest'
