// @ts-check

'use strict'

/**
 * Synthesizes Changesets files from Renovate `fix(deps)` commits so that
 * dependency updates produce patch bumps and changelog entries without anyone
 * manually committing changeset files.
 *
 * **fix(deps)** is used by Renovate to signify a _production_ dependency
 * update. Other dependency updates begin with `chore(deps)`, which this script
 * explicitly ignores!
 *
 * Run before `changesets/action` in CI — the action reads `.changeset/` as its
 * very first step and bails with no-op if the directory is empty, so we must
 * write files before it runs. Files written here are untracked; they are
 * consumed (and deleted) by `changeset version` and never appear in any
 * committed change.
 *
 * Pass `--dry-run` to preview what would be written without touching disk. Pass
 * `--bootstrap-sha` to use a specific commit as the release boundary instead of
 * detecting it automatically.
 *
 * @example
 *
 * ```sh
 * node scripts/changeset-deps.js          # write changeset files
 * node scripts/changeset-deps.js --dry-run
 * node scripts/changeset-deps.js --bootstrap-sha=abc123
 * ```
 *
 * @packageDocumentation
 */

const { execFile } = require('node:child_process')
const { parseArgs, promisify } = require('node:util')
const { mkdir, readFile, writeFile } = require('node:fs/promises')
const path = require('node:path')
const { glob } = require('glob')
const execFileAsync = promisify(execFile)

/**
 * Absolute path to the workspace root
 */
const ROOT = path.resolve(__dirname, '..')

/**
 * Maximum dir depth at which we expect a workspace to live
 */
const MAX_DEPTH = 3

/**
 * A function that runs a git command and returns its `STDOUT` trimmed of
 * trailing whitespace.
 *
 * @callback GitRunner
 * @param {string[]} args Git command arguments
 * @param {object} [extraOpts] Additional options to pass to
 *   {@link execFileAsync}
 * @returns {Promise<string>}
 */

/**
 * Runtime dependency fields that justify a patch release when updated.
 *
 * @typedef {'dependencies' | 'peerDependencies' | 'optionalDependencies'} RuntimeField
 */

/**
 * A runtime dependency change as detected by {@link getRuntimeDepChanges}.
 *
 * @typedef RuntimeDepChange
 * @property {RuntimeField} field Field name (e.g. `"dependencies"`)
 * @property {string} name Package name
 * @property {string} from Previous version (empty string if added)
 * @property {string} to New version (empty string if removed)
 */

/**
 * Represents a changeset `.md` file that needs to be written; generated by
 * {@link computeChangesets}.
 *
 * @typedef PendingChangeset
 * @property {string} filePath Absolute path to the changeset file
 * @property {string} content Markdown content of the changeset file
 * @property {string[]} pkgNames Npm names of every package the commit bumps,
 *   sorted
 * @property {string} sha Commit SHA; each commit yields at most one changeset
 */

/**
 * Information about a `fix(deps...)` commit as detected by
 * {@link findFixDepsCommits}.
 *
 * @typedef DepsCommit
 * @property {string} sha Commit SHA
 * @property {string} subject Commit subject
 * @property {string} summary Commit summary
 */

/**
 * Runtime dependency fields that justify a patch release when updated.
 * `devDependencies` is intentionally excluded: a `chore(deps)` that only
 * touches dev deps should not trigger a version bump.
 *
 * @satisfies {ReadonlyArray<RuntimeField>}
 */
const RUNTIME_FIELDS = Object.freeze(
  /** @type {const} */ ([
    'dependencies',
    'peerDependencies',
    'optionalDependencies',
  ])
)

/**
 * Matches a Renovate-style `fix(deps...)` conventional-commit subject. Capture
 * group 1 is the body text after the colon (e.g. `"update dependency yaml to
 * ^2.9.0 (#2113)"`).
 */
const FIX_DEPS_RE = /^fix\(deps[^)]*\)!?:\s*(.+)$/

/**
 * Logs message to stderr
 *
 * No-op in test env
 */
const log =
  process.env.NODE_ENV === 'test'
    ? /** @param {string} _message */
      (_message) => {}
    : /** @param {string} message */
      (message) => console.error(`[changeset-deps] ${message}`)

/**
 * Asserts a list of workspace patterns aren't sketchy.
 *
 * @param {string[]} patterns
 * @param {string} cwd
 * @returns {void}
 * @throws {Error} If a pattern escapes the workspace root
 */
const assertValidWorkspacePatterns = (patterns, cwd) => {
  for (const pattern of patterns) {
    const bare = pattern.startsWith('!') ? pattern.slice(1) : pattern
    const normalized = path.posix.normalize(bare.replaceAll('\\', '/'))
    if (
      path.posix.isAbsolute(normalized) ||
      path.win32.isAbsolute(bare) ||
      normalized === '..' ||
      normalized.startsWith('../')
    ) {
      throw new Error(
        `Workspace pattern "${pattern}" escapes the workspace root (${cwd})`
      )
    }
  }
}

/**
 * Factory for a `git` runner bound to a working directory.
 *
 * The runner returns `STDOUT` trimmed of trailing whitespace.
 *
 * @param {string} cwd
 * @returns {(args: string[], extraOpts?: object) => Promise<string>}
 */
const makeGitRunner =
  (cwd) =>
  async (args, extraOpts = {}) =>
    execFileAsync('git', args, {
      cwd,
      ...extraOpts,
      encoding: 'utf8',
    }).then((result) => result.stdout.trimEnd())

/**
 * Find the SHA that delimits "since the last release".
 *
 * Strategy:
 *
 * 1. Newest commit whose subject is exactly `'chore: version packages'` (the
 *    string pinned by `commit-message:` in the workflow, so it is
 *    self-maintaining).
 * 2. Fallback: the nearest tag reachable from `HEAD`. Before the first Changesets
 *    release, this is the last release-please release.
 * 3. Neither found → throws; never scans all of history blindly.
 *
 * @param {GitRunner} git
 * @returns {Promise<string>} Boundary SHA (exclusive lower bound for the scan
 *   range)
 */
const findBoundarySha = async (git) => {
  // Read subject + sha for every reachable commit in one shot.
  // Field separator: U+001F (unit separator).  Record separator: U+001E.
  const raw = await git(['log', '--format=%H%x1f%s%x1e', 'HEAD'])
  for (const entry of raw.split('\x1e')) {
    const trimmed = entry.trim()
    if (!trimmed) continue
    const sep = trimmed.indexOf('\x1f')
    if (sep === -1) continue
    const sha = trimmed.slice(0, sep).trim()
    const subject = trimmed.slice(sep + 1).trim()
    if (subject === 'chore: version packages') return sha
  }

  // Fallback: nearest tag reachable from HEAD. `describe` (rather than sorting
  // `git tag` output) guarantees the tag is an ancestor, so `<sha>..HEAD` is a
  // meaningful range.
  /** @type {string} */
  let tag
  try {
    tag = await git(['describe', '--tags', '--abbrev=0', 'HEAD'])
  } catch {
    throw new Error(
      'Cannot determine release boundary: no "chore: version packages" commit ' +
        'found, and no tag is reachable from HEAD'
    )
  }
  // Peel annotated tags down to the commit they point at.
  const sha = await git(['rev-parse', `${tag}^{commit}`])
  log(`No Changesets release commit found; falling back to tag ${tag} (${sha})`)
  return sha
}

/**
 * Return every `fix(deps*)` commit between `boundarySha` (exclusive) and HEAD,
 * in reverse-chronological order.
 *
 * @param {GitRunner} git Git executor
 * @param {string} boundarySha Boundary commit (exclusive lower bound for the
 *   scan range)
 * @returns {Promise<DepsCommit[]>}
 */
const findFixDepsCommits = async (git, boundarySha) => {
  const raw = await git([
    'log',
    '--format=%H%x1f%s%x1e',
    `${boundarySha}..HEAD`,
  ])
  /** @type {DepsCommit[]} */
  const commits = []
  for (const entry of raw.split('\x1e')) {
    const trimmed = entry.trim()
    if (!trimmed) continue
    const sep = trimmed.indexOf('\x1f')
    if (sep === -1) continue
    const sha = trimmed.slice(0, sep).trim()
    const subject = trimmed.slice(sep + 1).trim()
    const match = FIX_DEPS_RE.exec(subject)
    if (!match) continue
    // Strip the conventional-commit prefix and capitalise the first letter.
    const body = match[1]
    const summary = body.charAt(0).toUpperCase() + body.slice(1)
    commits.push({ sha, subject, summary })
  }
  return commits
}

/**
 * Discover the publishable workspaces declared by the root `package.json`.
 *
 * Expands the root `workspaces` globs (array form or `{ packages: [...] }`
 * form; `!`-prefixed patterns are treated as exclusions) and keeps only
 * manifests that have a `name` and are not `private: true`. Reads the working
 * tree rather than the installed dependency tree, so it works without
 * `node_modules`.
 *
 * @param {string} cwd Absolute path to the repo root
 * @returns {Promise<Map<string, string>>} Repo-relative POSIX manifest path →
 *   package name
 */
const getPublicWorkspaces = async (cwd) => {
  const rootManifestJson = await readFile(
    path.join(cwd, 'package.json'),
    'utf8'
  )
  const rootManifest = JSON.parse(rootManifestJson)

  /** @type {unknown} */
  const declared = Array.isArray(rootManifest.workspaces)
    ? rootManifest.workspaces
    : rootManifest.workspaces?.packages
  const patterns = Array.isArray(declared)
    ? declared.filter((p) => typeof p === 'string')
    : []

  assertValidWorkspacePatterns(patterns, cwd)

  /**
   * Appends `package.json` to a path.
   *
   * Because this is fed to {@link glob}, it should be POSIX-style.
   *
   * @param {string} p
   * @returns {string}
   */
  const withPkgJson = (p) => path.posix.join(p, 'package.json')

  const include = patterns.filter((p) => !p.startsWith('!')).map(withPkgJson)

  /**
   * Exclude patterns begin with a `!`. Because these are passed separately via
   * the `ignore` option to `glob` instead of inline, we strip the leading `!`.
   */
  const ignore = [
    ...patterns
      .filter((p) => p.startsWith('!'))
      .map(withPkgJson)
      .map((p) => p.slice(1)),
    '**/node_modules/**',
  ]

  const manifestPaths = await glob(include, {
    cwd,
    ignore,
    nodir: true,
    noext: true,
    nobrace: true,
    maxDepth: MAX_DEPTH,
  }).then((paths) => paths.toSorted())

  /** @type {Map<string, string>} */
  const workspaces = new Map()
  await Promise.all(
    manifestPaths.map(async (manifestPath) => {
      const manifestJson = await readFile(path.join(cwd, manifestPath), 'utf8')
      const manifest = JSON.parse(manifestJson)
      if (manifest.private === true) return
      if (typeof manifest.name !== 'string' || !manifest.name) return
      workspaces.set(manifestPath, manifest.name)
    })
  )

  return workspaces
}

/**
 * List the publishable workspace manifests touched by `sha`.
 *
 * @param {GitRunner} git
 * @param {string} sha
 * @param {ReadonlyMap<string, string>} workspaces Result of
 *   {@link getPublicWorkspaces}
 * @returns {Promise<string[]>} Repo-relative POSIX manifest paths
 */
const getChangedPackageJsonFiles = async (git, sha, workspaces) => {
  const out = await git([
    'diff-tree',
    '--no-commit-id',
    '-r',
    '--name-only',
    sha,
  ])
  return out
    .split('\n')
    .map((l) => l.trim())
    .filter((l) => workspaces.has(l))
}

/**
 * Parse a `package.json` blob from git at a given treeish ref. Returns `{}`
 * when the ref does not exist (file newly added in `sha`, or `sha` is the
 * initial commit).
 *
 * @param {GitRunner} git
 * @param {string} ref E.g. `"abc123^"` or `"abc123"`
 * @param {string} filePath Repo-relative path
 * @returns {Promise<Record<string, unknown>>}
 */
const readJsonAtRef = async (git, ref, filePath) => {
  try {
    return JSON.parse(await git(['show', `${ref}:${filePath}`]))
  } catch {
    return {}
  }
}

/**
 * Collect all runtime-dependency changes for a single `package.json` as
 * introduced by commit `sha`.
 *
 * @param {GitRunner} git
 * @param {string} sha
 * @param {string} pkgJsonPath Repo-relative path to `package.json`
 * @returns {Promise<RuntimeDepChange[]>}
 */
const getRuntimeDepChanges = async (git, sha, pkgJsonPath) => {
  const [before, after] = await Promise.all([
    readJsonAtRef(git, `${sha}^`, pkgJsonPath),
    readJsonAtRef(git, sha, pkgJsonPath),
  ])

  /** @type {RuntimeDepChange[]} */
  const changes = []
  for (const field of RUNTIME_FIELDS) {
    const bMap = /** @type {Record<string, string>} */ (before[field] ?? {})
    const aMap = /** @type {Record<string, string>} */ (after[field] ?? {})
    const keys = new Set([...Object.keys(bMap), ...Object.keys(aMap)])
    for (const name of keys) {
      if (bMap[name] !== aMap[name]) {
        changes.push({
          field,
          name,
          from: bMap[name] ?? '(added)',
          to: aMap[name] ?? '(removed)',
        })
      }
    }
  }
  return changes
}

/**
 * Build the markdown content of a changeset file.
 *
 * The summary's `(#NNNN)` references are intentionally left as plain text:
 * `@changesets/changelog-github` runs `linkifyIssueRefs` over every summary
 * line, turning them into proper hyperlinks without the thank-you message that
 * a `pr:` directive would add.
 *
 * Every package is listed in the front matter with a `patch` bump, so the one
 * summary appears in each package's changelog. When the commit made more than
 * one distinct runtime dep change (deduplicated across packages), continuation
 * lines are appended; `@changesets/changelog-github` indents them two spaces,
 * producing a nested list in the generated changelog.
 *
 * @param {string[]} pkgNames Npm package names to bump
 * @param {string} summary First-line description (capitalised commit body)
 * @param {RuntimeDepChange[]} depChanges Changes across all of `pkgNames`
 * @returns {string}
 */
const buildChangesetContent = (pkgNames, summary, depChanges) => {
  const releases = pkgNames.map((name) => `'${name}': patch`).join('\n')
  const frontmatter = `---\n${releases}\n---\n`

  /** @type {Map<string, RuntimeDepChange>} */
  const distinct = new Map()
  for (const change of depChanges) {
    distinct.set(`${change.name}\0${change.from}\0${change.to}`, change)
  }

  let body = summary
  if (distinct.size > 1) {
    const lines = [...distinct.values()].map(
      ({ name, from, to }) => `  - \`${name}\`: \`${from}\` → \`${to}\``
    )
    body += '\n\n' + lines.join('\n')
  }
  return `${frontmatter}\n${body}\n`
}

/**
 * Validate a user-supplied boundary and expand it to a full commit SHA.
 *
 * The commit must exist and be an ancestor of `HEAD`; otherwise `<sha>..HEAD`
 * would silently include history from wherever the two lines of development
 * diverged.
 *
 * @param {GitRunner} git
 * @param {string} bootstrapSha Full or abbreviated commit SHA
 * @returns {Promise<string>} Full commit SHA
 */
const resolveBootstrapSha = async (git, bootstrapSha) => {
  /** @type {string} */
  let sha
  try {
    sha = await git(['rev-parse', '--verify', `${bootstrapSha}^{commit}`])
  } catch {
    throw new Error(`Bootstrap SHA "${bootstrapSha}" is not a known commit`)
  }
  try {
    await git(['merge-base', '--is-ancestor', sha, 'HEAD'])
  } catch {
    throw new Error(
      `Bootstrap SHA "${bootstrapSha}" is not an ancestor of HEAD`
    )
  }
  log(`Using bootstrap SHA ${sha} as the release boundary`)
  return sha
}

/**
 * Core computation: determine all changeset files that need to be written.
 *
 * This is a pure function (modulo git I/O and filesystem reads) that accepts an
 * injected `git` runner so tests can point it at a throw-away repo.
 *
 * @param {GitRunner} git
 * @param {string} cwd Absolute path to the repo root (for reading working-tree
 *   files)
 * @param {object} [options]
 * @param {string} [options.bootstrapSha] Boundary commit to use instead of
 *   {@link findBoundarySha}'s detection
 * @returns {Promise<PendingChangeset[]>}
 */
const computeChangesets = async (git, cwd, { bootstrapSha } = {}) => {
  const [boundarySha, workspaces] = await Promise.all([
    bootstrapSha === undefined
      ? findBoundarySha(git)
      : resolveBootstrapSha(git, bootstrapSha),
    getPublicWorkspaces(cwd),
  ])
  const commits = await findFixDepsCommits(git, boundarySha)

  /** @type {(PendingChangeset | undefined)[]} */
  const results = await Promise.all(
    commits.map(async ({ sha, summary }) => {
      const changedPackageJsonFiles = await getChangedPackageJsonFiles(
        git,
        sha,
        workspaces
      )

      const perPackage = await Promise.all(
        changedPackageJsonFiles.map(async (pkgJsonPath) => ({
          pkgName: /** @type {string} */ (workspaces.get(pkgJsonPath)),
          depChanges: await getRuntimeDepChanges(git, sha, pkgJsonPath),
        }))
      )
      const bumped = perPackage.filter(({ depChanges }) => depChanges.length)
      if (bumped.length === 0) return undefined

      const pkgNames = bumped.map(({ pkgName }) => pkgName).sort()
      const content = buildChangesetContent(
        pkgNames,
        summary,
        bumped.flatMap(({ depChanges }) => depChanges)
      )
      const filePath = path.join(
        cwd,
        '.changeset',
        `renovate-${sha.slice(0, 7)}.md`
      )
      return { filePath, content, pkgNames, sha }
    })
  )

  return results.filter((result) => result !== undefined)
}

// ---------------------------------------------------------------------------
// Entry point
// ---------------------------------------------------------------------------

/**
 * Write (or preview) synthesized changeset files.
 *
 * @param {object} [options]
 * @param {boolean} [options.dryRun] Print instead of writing
 * @param {string} [options.cwd] Repo root (defaults to package root)
 * @param {string} [options.bootstrapSha] Boundary commit overriding detection
 * @returns {Promise<void>}
 */
const main = async ({ dryRun = false, cwd = ROOT, bootstrapSha } = {}) => {
  const git = makeGitRunner(cwd)
  const changesets = await computeChangesets(git, cwd, { bootstrapSha })

  if (changesets.length === 0) {
    log('No dependency changesets to synthesize')
    return
  }

  for (const { filePath, content, pkgNames, sha } of changesets) {
    const rel = path.relative(cwd, filePath)
    const what = `${pkgNames.join(', ')} @ ${sha.slice(0, 7)}`
    if (dryRun) {
      log(`dry-run: would write ${rel} (${what})`)
      console.log(content)
    } else {
      await mkdir(path.dirname(filePath), { recursive: true })
      await writeFile(filePath, content, 'utf8')
      log(`Wrote ${rel} (${what})`)
    }
  }
}

/**
 * Parse command-line flags and run {@link main}. Unknown flags are an error so
 * that a typo like `--dryrun` cannot silently fall through to a real write.
 *
 * @param {string[]} [args] Defaults to `process.argv.slice(2)`
 * @returns {Promise<void>}
 */
const cli = async (args = process.argv.slice(2)) => {
  /** @type {{ 'dry-run': boolean; 'bootstrap-sha'?: string }} */
  let values
  try {
    ;({ values } = parseArgs({
      args,
      options: {
        'dry-run': { type: 'boolean', default: false },
        // Overrides boundary detection entirely
        'bootstrap-sha': { type: 'string' },
      },
      strict: true,
    }))
  } catch (/** @type {any} */ err) {
    log(err)
    process.exitCode = 1
    return
  }
  await main({
    dryRun: values['dry-run'],
    bootstrapSha: values['bootstrap-sha'],
  })
}

if (require.main === module) {
  void cli()
}

module.exports = {
  buildChangesetContent,
  computeChangesets,
  findBoundarySha,
  findFixDepsCommits,
  getChangedPackageJsonFiles,
  getPublicWorkspaces,
  getRuntimeDepChanges,
  makeGitRunner,
  resolveBootstrapSha,
}
