FROM docker.io/library/node:18-alpine@sha256:3482a20c97e401b56ac50ba8920cc7b5b2022bfc6aa7d4e4c231755770cf892f
WORKDIR /app

RUN apk add --no-cache git && \
  chown node:node /app

COPY --chown=node:node . .
USER node

RUN git config --global user.email "you@example.com" && \
  git config --global user.name "Your Name" && \
  npm config set prefix '~/.local/' && \
  npm install && \
  npm run setup && \
  npm run build && \
  mkdir -p /app/verdaccio/storage && \
  npm i -g verdaccio && \
  rm /home/node/.npmrc

ENV PATH="/home/node/.local/bin:$PATH"
ENTRYPOINT ["/usr/local/bin/npm"]
