name: Validate Commit Messages
on: [pull_request]

permissions:
  contents: read

jobs:
  commitlint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false
          fetch-depth: 0
      - uses: ./.github/actions/prepare
        with:
          node-version: 24.x
      - name: Validate PR commits with commitlint
        env:
          FROM_SHA: ${{ github.event.pull_request.base.sha }}
          TO_SHA: ${{ github.event.pull_request.head.sha }}
        run: npx commitlint --from "${FROM_SHA}" --to "${TO_SHA}" --verbose
