name: Validate Commit Messages
on: [pull_request]

permissions:
  contents: read

jobs:
  commitlint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false
          fetch-depth: 0
      - uses: ./.github/actions/prepare
        with:
          node-version: 24.x
      - name: Validate PR commits with commitlint
        env:
          FROM_SHA: ${{ github.event.pull_request.base.sha }}
          TO_SHA: ${{ github.event.pull_request.head.sha }}
        run: npx --offline commitlint --from "${FROM_SHA}" --to "${TO_SHA}" --verbose
