name: LabelBot
on:
  - pull_request_target

permissions:
  contents: read

jobs:
  labeler:
    permissions:
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - name: Label PRs
        uses: actions/labeler@8558fd74291d67161a8a78ce36a881fa63b766a9 # v5
