name: Add new PR to review board

permissions:
  issues: read
  pull-requests: read
  repository-projects: write

on:
  pull_request:
    types:
      - opened

jobs:
  add-to-project:
    name: Add new PR to review board
    if: github.event.pull_request.user.login != 'renovate[bot]'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/add-to-project@244f685bbc3b7adfa8466e08b698b5577571133e # v1
        with:
          project-url: https://github.com/orgs/LavaMoat/projects/7
          github-token: ${{ secrets.PR_QUEUE_PAT }}
