# this workflow automatically creates release PRs when something gets merged into the main branch.
# we're using the strategy documented here https://github.com/googleapis/release-please/blob/main/docs/manifest-releaser.md

on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

name: release-please

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: googleapis/release-please-action@5c625bfb5d1ff62eadeeb3772007f7f66fdcf071 # v4
