on:
  workflow_dispatch:
    inputs:
      run_id:
        description: 'The ID of the workflow run to rerun'
        required: true
      runner:
        description: 'The runner to use for the rerun'
        required: true

permissions: {}

jobs:
  rerun:
    permissions:
      actions: write
    runs-on: ${{ inputs.runner }}
    steps:
      - name: rerun ${{ inputs.run_id }}
        env:
          GH_REPO: ${{ github.repository }}
          GH_TOKEN: ${{ github.token }}
          GH_DEBUG: api
          RUN_ID: ${{ inputs.run_id }}
        run: |
          gh run watch "${RUN_ID}"
          gh run rerun "${RUN_ID}" --failed
